#!/usr/bin/env bash
# cmd-explain.sh -- Plain-language explanations of toolkit concepts
#
# Sourced by toolkit.sh. Expects: TOOLKIT_DIR and helper functions.

cmd_explain() {
  local topic="${1:-overview}"
  case "$topic" in
    overview)
      echo "Claude Toolkit is a collection of hooks, agents, skills, and rules"
      echo "that integrate into your .claude/ directory for safe, autonomous AI development."
      echo ""
      echo "Components:"
      echo "  hooks/   -- Scripts that run automatically (guards, linting, quality gates)"
      echo "  agents/  -- Prompts for specialized AI agents (reviewer, qa, security, etc.)"
      echo "  skills/  -- Templates for common workflows (review, implement, plan, etc.)"
      echo "  rules/   -- Coding convention documents loaded by Claude Code"
      echo ""
      echo "Run '$0 explain <topic>' for details on:"
      echo "  hooks, agents, skills, rules, config, stacks"
      ;;
    hooks)
      echo "Hooks are scripts (mostly shell, one Python) that Claude Code runs"
      echo "automatically at lifecycle events."
      echo "You do not invoke them manually -- they fire in response to events."
      echo ""
      echo "Categories:"
      echo "  Guards         -- Block dangerous operations (destructive git, secret writes)"
      echo "  Automation     -- Auto-approve safe operations (file reads, linters)"
      echo "  Quality gates  -- Run checks after edits or before task completion"
      echo "  Lifecycle      -- Manage session state (setup, cleanup, compaction)"
      echo "  Subagent       -- Inject context into and validate spawned sub-agents"
      echo ""
      echo "All hooks read config from _config.sh, which sources toolkit-cache.env."
      echo "Configure hook behavior in toolkit.toml -- no script editing needed."
      echo ""
      echo "Hook files (in hooks/):"
      echo "  guard-destructive.sh       -- Blocks git push, rm -rf, eval, pipe-to-shell"
      echo "  guard-sensitive-writes.sh  -- Blocks writes to .env, credentials, .git/"
      echo "  auto-approve-safe.sh       -- Auto-approves Read/Glob/Grep and safe commands"
      echo "  post-edit-lint.sh          -- Runs linter/formatter after file edits"
      echo "  task-completed-gate.sh     -- Quality gates before task completion"
      echo "  classify-error.sh          -- Classifies tool errors, suggests recovery"
      echo "  setup.sh                   -- Validates dev environment on session start"
      echo "  session-start.sh           -- Loads project state"
      echo "  session-end-cleanup.sh     -- Cleans temp files, truncates logs"
      echo "  pre-compact.sh             -- Saves state before context compaction"
      echo "  post-compact-reinject.sh   -- Restores context after compaction"
      echo "  subagent-context-inject.sh -- Injects project context into subagents"
      echo "  verify-completion.sh       -- Warns about uncommitted changes"
      echo "  smart-context.py           -- Keyword-based domain context loading"
      echo "  notify.sh                  -- Platform-aware notifications"
      echo "  _config.sh                 -- Shared configuration (sourced by all hooks)"
      ;;
    agents)
      echo "Agents are markdown prompt files defining specialized AI personas."
      echo "They are symlinked from the toolkit into .claude/agents/."
      echo ""
      echo "Available agents (10 total):"
      echo "  reviewer.md     -- Adversarial code review: bugs, missing tests, security"
      echo "  qa.md           -- Test execution, validation, coverage analysis"
      echo "  security.md     -- Secrets scanning, SAST, dependency vulnerabilities"
      echo "  ux.md           -- Accessibility (WCAG 2.1 AA), VoiceOver, dark mode"
      echo "  pm.md           -- Product perspective, user workflows, edge cases"
      echo "  docs.md         -- Documentation accuracy, code-doc sync"
      echo "  architect.md    -- Deep architecture analysis, patterns, resiliency"
      echo "  commit-check.md -- Lightweight post-commit sanity check"
      echo "  plan.md         -- Feature planning with research and scope analysis"
      echo "  gemini.md       -- Gemini CLI relay for second opinions"
      echo ""
      echo "Configuration ([agents] section in toolkit.toml):"
      echo "  agents.install controls which agents are symlinked into .claude/agents/."
      echo "  Default: [\"reviewer\", \"commit-check\"] (~8.5KB of system prompt)"
      echo "  All agents: [\"all\"] (~49KB) | No agents: [\"none\"]"
      echo ""
      echo "Context trade-off:"
      echo "  Installed agents are loaded into Claude's system prompt on every turn."
      echo "  This is efficient per invocation (~1KB for a Task call) but adds to the"
      echo "  always-on context cost. Uninstalled agents have zero system prompt cost"
      echo "  but use more context when invoked on-demand (~10KB per fallback call)."
      echo ""
      echo "General-purpose fallback:"
      echo "  Skills that need an uninstalled agent (e.g., /review security) will"
      echo "  automatically read the agent prompt from .claude/toolkit/agents/ and"
      echo "  launch with subagent_type=\"general-purpose\" instead. This means all"
      echo "  skills continue to work regardless of which agents are installed."
      echo ""
      echo "Agent prompts are generic by design -- no project-specific content."
      echo "Project context is injected at runtime by the subagent-context hook."
      echo ""
      echo "To customize an agent: toolkit.sh customize agents/<name>.md"
      ;;
    skills)
      echo "Skills are workflow templates triggered by slash commands in Claude Code."
      echo "Each skill is a SKILL.md file describing a multi-step procedure."
      echo ""
      echo "Available skills:"
      echo "  /toolkit-setup     -- Set up or reconfigure the toolkit for a project"
      echo "  /toolkit-update    -- Update the toolkit to a new version"
      echo "  /toolkit-doctor    -- Deep health evaluation and optimization"
      echo "  /toolkit-contribute -- Upstream generic improvements to the toolkit"
      echo "  /review-suite   -- Multi-agent code review orchestration"
      echo "  /implement      -- Autonomous plan execution with milestone agents"
      echo "  /plan           -- Feature planning with research and review"
      echo "  /fix-github     -- GitHub issue workflow (fetch, reproduce, fix, commit)"
      echo "  /fix            -- Standalone bug fix without GitHub issue"
      echo "  /loop           -- Iterative evaluate-fix-validate convergence loop"
      echo "  /conventions    -- View coding conventions for a domain"
      echo "  /scope-resolver -- Resolve feature scopes for review targeting"
      echo ""
      echo "Skills are copied (not symlinked) during init, so you can customize them."
      echo "To mark a skill as customized: toolkit.sh customize skills/<name>/SKILL.md"
      ;;
    rules)
      echo "Rules are coding convention documents loaded by Claude Code as context."
      echo "They tell Claude how to write code for your project."
      echo ""
      echo "Generic rules (always included):"
      echo "  git-protocol.md  -- Git staging, commit message format, branching"
      echo ""
      echo "Stack-specific rule templates (applied based on project.stacks):"
      echo "  python.md            -- Python 3.11+ conventions, ruff, type hints"
      echo "  swift.md             -- SwiftUI, HealthKit/HomeKit patterns"
      echo "  typescript.md        -- TypeScript/Node conventions"
      echo "  testing-pytest.md    -- pytest patterns and fixtures"
      echo "  testing-jest.md      -- Jest testing patterns"
      echo "  api-routes-fastapi.md -- FastAPI route conventions"
      echo "  database-sqlite.md   -- SQLite WAL mode patterns"
      echo ""
      echo "Rule templates are copied during init, so you can edit them freely."
      ;;
    config)
      echo "Configuration flows through three layers:"
      echo ""
      echo "1. toolkit.toml -- Your project's config file (in .claude/)"
      echo "   Controls hook behavior, quality gates, linters, notifications, and more."
      echo ""
      echo "2. Config cache (toolkit-cache.env) -- Generated bash env vars"
      echo "   Hooks source this for fast access without parsing TOML at runtime."
      echo "   Regenerated by: toolkit.sh generate-settings"
      echo ""
      echo "3. Three-tier settings merge:"
      echo "   Base (settings-base.json) + Stack overlays + Project overrides"
      echo "   Produces settings.json (Claude Code reads this) and .mcp.json"
      echo ""
      echo "Key config sections in toolkit.toml:"
      echo "  [toolkit]              -- Remote URL for updates"
      echo "  [project]              -- Name, version file, stacks"
      echo "  [hooks.setup]          -- Required/optional tools"
      echo "  [hooks.post-edit-lint] -- Per-extension linter/formatter config"
      echo "  [hooks.task-completed] -- Quality gates (lint, tests)"
      echo "  [hooks.auto-approve]   -- Auto-approved write paths and commands"
      echo "  [hooks.subagent-context] -- Context injected into subagents"
      echo "  [hooks.compact]        -- Pre-compact state preservation"
      echo "  [hooks.session-end]    -- Cleanup thresholds"
      echo "  [notifications]        -- App name, sound settings"
      echo ""
      echo "See docs/reference.md for the full configuration reference."
      ;;
    stacks)
      echo "Stacks represent your project's technology profile."
      echo "Set them in toolkit.toml: project.stacks = [\"python\", \"typescript\"]"
      echo ""
      echo "Available stacks:"
      echo "  python      -- Python-specific hook matchers, deny patterns, ruff linting"
      echo "  ios         -- iOS/Swift-specific hook matchers"
      echo "  typescript  -- TypeScript/Node-specific hook matchers, npm patterns"
      echo ""
      echo "When you configure stacks, two things happen:"
      echo ""
      echo "  1. Settings overlays -- Each stack merges additional hook matchers"
      echo "     and deny patterns into your settings.json"
      echo ""
      echo "  2. Rule templates -- Stack-specific coding conventions are copied"
      echo "     into .claude/rules/ (e.g., python.md, testing-pytest.md)"
      echo ""
      echo "Multiple stacks can be combined (e.g., a Python API + TypeScript frontend)."
      ;;
    -h|--help)
      echo "Usage: $0 explain [topic]"
      echo ""
      echo "Available topics: overview, hooks, agents, skills, rules, config, stacks"
      ;;
    *)
      echo "Unknown topic: $topic"
      echo ""
      echo "Available topics: overview, hooks, agents, skills, rules, config, stacks"
      echo ""
      echo "Usage: $0 explain [topic]"
      return 1
      ;;
  esac
}
