#!/bin/bash
# Shared configuration helper sourced by every hook.
# Hooks call: source "$(dirname "$0")/_config.sh"
#
# Reads cached configuration from toolkit-cache.env (generated by toolkit.sh).
# Falls back to sensible defaults if no cache exists.

export TOOLKIT_DIR
TOOLKIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE_FILE="${CLAUDE_PROJECT_DIR:-.}/.claude/toolkit-cache.env"
TOML_FILE="${CLAUDE_PROJECT_DIR:-.}/.claude/toolkit.toml"

if [ -f "$CACHE_FILE" ]; then
  # shellcheck source=/dev/null
  source "$CACHE_FILE"
  # Warn if TOML is newer than cache (user edited config but hasn't regenerated)
  if [ -f "$TOML_FILE" ] && [ "$TOML_FILE" -nt "$CACHE_FILE" ]; then
    echo "Warning: toolkit.toml is newer than toolkit-cache.env. Run: toolkit.sh generate-settings" >&2
  fi
else
  # Defaults when no cache exists
  TOOLKIT_PROJECT_NAME="${TOOLKIT_PROJECT_NAME:-unknown}"
  TOOLKIT_STACKS="${TOOLKIT_STACKS:-}"
  TOOLKIT_VERSION_FILE="${TOOLKIT_VERSION_FILE:-VERSION}"
  TOOLKIT_GUARD_ENABLED="${TOOLKIT_GUARD_ENABLED:-true}"
  TOOLKIT_NOTIFY_APP_NAME="${TOOLKIT_NOTIFY_APP_NAME:-Claude Code}"
  TOOLKIT_NOTIFY_SOUND="${TOOLKIT_NOTIFY_SOUND:-Blow}"
fi
