#!/usr/bin/env bash
# Shared configuration helper sourced by every hook.
# Hooks call: source "$(dirname "$0")/_config.sh"
#
# Reads cached configuration from toolkit-cache.env (generated by generate-config-cache.py).
# Falls back to sensible defaults if no cache exists.

# --- Bash version compatibility check ---
# Most hooks work with bash 3.2 (macOS default). Warn if older.
if [ "${BASH_VERSINFO[0]}" -lt 3 ] || { [ "${BASH_VERSINFO[0]}" -eq 3 ] && [ "${BASH_VERSINFO[1]}" -lt 2 ]; }; then
  echo "[toolkit:_config] WARN: claude-toolkit requires bash 3.2+, found ${BASH_VERSION}" >&2
fi

export TOOLKIT_DIR
TOOLKIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE_FILE="${CLAUDE_PROJECT_DIR:-.}/.claude/toolkit-cache.env"
TOML_FILE="${CLAUDE_PROJECT_DIR:-.}/.claude/toolkit.toml"

# Config caching optimization: skip re-sourcing if already loaded and cache
# file mtime hasn't changed. Uses _TOOLKIT_CONFIG_LOADED to track state.
_should_reload_config=true
if [ -n "${_TOOLKIT_CONFIG_LOADED:-}" ] && [ -f "$CACHE_FILE" ]; then
  _current_mtime=""
  if command -v stat >/dev/null 2>&1; then
    # macOS stat uses -f, Linux stat uses -c
    _current_mtime=$(stat -f '%m' "$CACHE_FILE" 2>/dev/null || stat -c '%Y' "$CACHE_FILE" 2>/dev/null || true)
  fi
  if [ -n "$_current_mtime" ] && [ "$_current_mtime" = "$_TOOLKIT_CONFIG_LOADED" ]; then
    _should_reload_config=false
  fi
fi

if [ "$_should_reload_config" = true ] && [ -f "$CACHE_FILE" ]; then
  # shellcheck source=/dev/null
  source "$CACHE_FILE"
  # Record mtime so subsequent hook invocations can skip re-sourcing
  if command -v stat >/dev/null 2>&1; then
    _TOOLKIT_CONFIG_LOADED=$(stat -f '%m' "$CACHE_FILE" 2>/dev/null || stat -c '%Y' "$CACHE_FILE" 2>/dev/null || true)
    export _TOOLKIT_CONFIG_LOADED
  fi
fi

# Warn if toolkit.toml exists but cache is missing entirely (hooks will use
# defaults instead of project-specific configuration — a silent footgun)
if [ -f "$TOML_FILE" ] && [ ! -f "$CACHE_FILE" ]; then
  echo "[toolkit:_config] WARN: toolkit-cache.env is missing. Hooks are using defaults, not your toolkit.toml settings." >&2
  echo "[toolkit:_config] WARN: Run: python3 generate-config-cache.py --toml .claude/toolkit.toml --output .claude/toolkit-cache.env" >&2
# Warn if TOML is newer than cache (always check, even with cached config)
elif [ -f "$TOML_FILE" ] && [ -f "$CACHE_FILE" ] && [ "$TOML_FILE" -nt "$CACHE_FILE" ]; then
  echo "[toolkit:_config] WARN: toolkit.toml is newer than toolkit-cache.env. Run: python3 generate-config-cache.py --toml .claude/toolkit.toml --output .claude/toolkit-cache.env" >&2
fi

# ---------------------------------------------------------------------------
# Defaults — applied when no cache exists or a key is missing
# ---------------------------------------------------------------------------

# Project
TOOLKIT_PROJECT_NAME="${TOOLKIT_PROJECT_NAME:-unknown}"
TOOLKIT_PROJECT_VERSION_FILE="${TOOLKIT_PROJECT_VERSION_FILE:-VERSION}"
TOOLKIT_PROJECT_STACKS="${TOOLKIT_PROJECT_STACKS:-}"

# Guards
TOOLKIT_GUARD_ENABLED="${TOOLKIT_GUARD_ENABLED:-true}"

# Setup
TOOLKIT_HOOKS_SETUP_PYTHON_MIN_VERSION="${TOOLKIT_HOOKS_SETUP_PYTHON_MIN_VERSION:-3.11}"
TOOLKIT_HOOKS_SETUP_REQUIRED_TOOLS="${TOOLKIT_HOOKS_SETUP_REQUIRED_TOOLS:-[\"ruff\",\"jq\"]}"
TOOLKIT_HOOKS_SETUP_OPTIONAL_TOOLS="${TOOLKIT_HOOKS_SETUP_OPTIONAL_TOOLS:-[]}"
TOOLKIT_HOOKS_SETUP_SECURITY_TOOLS="${TOOLKIT_HOOKS_SETUP_SECURITY_TOOLS:-[]}"

# Post-edit lint (per-extension; defaults for Python)
TOOLKIT_HOOKS_POST_EDIT_LINT_LINTERS_PY_CMD="${TOOLKIT_HOOKS_POST_EDIT_LINT_LINTERS_PY_CMD:-.venv/bin/ruff check}"
TOOLKIT_HOOKS_POST_EDIT_LINT_LINTERS_PY_FMT="${TOOLKIT_HOOKS_POST_EDIT_LINT_LINTERS_PY_FMT:-.venv/bin/ruff format}"
TOOLKIT_HOOKS_POST_EDIT_LINT_LINTERS_PY_FALLBACK="${TOOLKIT_HOOKS_POST_EDIT_LINT_LINTERS_PY_FALLBACK:-ruff}"

# Task-completed gates (defaults for Python lint)
TOOLKIT_HOOKS_TASK_COMPLETED_GATES_LINT_GLOB="${TOOLKIT_HOOKS_TASK_COMPLETED_GATES_LINT_GLOB:-*.py}"
TOOLKIT_HOOKS_TASK_COMPLETED_GATES_LINT_CMD="${TOOLKIT_HOOKS_TASK_COMPLETED_GATES_LINT_CMD:-.venv/bin/ruff check --quiet}"
TOOLKIT_HOOKS_TASK_COMPLETED_GATES_TESTS_GLOB="${TOOLKIT_HOOKS_TASK_COMPLETED_GATES_TESTS_GLOB:-*.py}"
TOOLKIT_HOOKS_TASK_COMPLETED_GATES_TESTS_CMD="${TOOLKIT_HOOKS_TASK_COMPLETED_GATES_TESTS_CMD:-make test-changed}"
TOOLKIT_HOOKS_TASK_COMPLETED_GATES_TESTS_TIMEOUT="${TOOLKIT_HOOKS_TASK_COMPLETED_GATES_TESTS_TIMEOUT:-90}"

# Auto-approve
TOOLKIT_HOOKS_AUTO_APPROVE_WRITE_PATHS="${TOOLKIT_HOOKS_AUTO_APPROVE_WRITE_PATHS:-[]}"
TOOLKIT_HOOKS_AUTO_APPROVE_BASH_COMMANDS="${TOOLKIT_HOOKS_AUTO_APPROVE_BASH_COMMANDS:-[]}"
TOOLKIT_HOOKS_AUTO_APPROVE_MCP_TOOL_PREFIXES="${TOOLKIT_HOOKS_AUTO_APPROVE_MCP_TOOL_PREFIXES:-[\"mcp__codex__\",\"mcp__plugin_playwright_playwright__\",\"mcp__plugin_context7_context7__\"]}"

# Subagent context
TOOLKIT_HOOKS_SUBAGENT_CONTEXT_CRITICAL_RULES="${TOOLKIT_HOOKS_SUBAGENT_CONTEXT_CRITICAL_RULES:-[]}"
TOOLKIT_HOOKS_SUBAGENT_CONTEXT_AVAILABLE_TOOLS="${TOOLKIT_HOOKS_SUBAGENT_CONTEXT_AVAILABLE_TOOLS:-[]}"
TOOLKIT_HOOKS_SUBAGENT_CONTEXT_STACK_INFO="${TOOLKIT_HOOKS_SUBAGENT_CONTEXT_STACK_INFO:-}"

# Compact
TOOLKIT_HOOKS_COMPACT_SOURCE_DIRS="${TOOLKIT_HOOKS_COMPACT_SOURCE_DIRS:-[\"src\",\"app\",\"lib\"]}"
TOOLKIT_HOOKS_COMPACT_SOURCE_EXTENSIONS="${TOOLKIT_HOOKS_COMPACT_SOURCE_EXTENSIONS:-[\"*.py\"]}"
TOOLKIT_HOOKS_COMPACT_STATE_DIRS="${TOOLKIT_HOOKS_COMPACT_STATE_DIRS:-[\"artifacts\"]}"

# Session-end
TOOLKIT_HOOKS_SESSION_END_AGENT_MEMORY_MAX_LINES="${TOOLKIT_HOOKS_SESSION_END_AGENT_MEMORY_MAX_LINES:-250}"
TOOLKIT_HOOKS_SESSION_END_HOOK_LOG_MAX_LINES="${TOOLKIT_HOOKS_SESSION_END_HOOK_LOG_MAX_LINES:-500}"

# Skills — implement
TOOLKIT_SKILLS_IMPLEMENT_TDD_ENFORCEMENT="${TOOLKIT_SKILLS_IMPLEMENT_TDD_ENFORCEMENT:-off}"

# Agents
TOOLKIT_AGENTS_INSTALL="${TOOLKIT_AGENTS_INSTALL:-[\"reviewer\",\"commit-check\"]}"

# Notifications
TOOLKIT_NOTIFICATIONS_APP_NAME="${TOOLKIT_NOTIFICATIONS_APP_NAME:-Claude Code}"
TOOLKIT_NOTIFICATIONS_PERMISSION_SOUND="${TOOLKIT_NOTIFICATIONS_PERMISSION_SOUND:-Blow}"

# Debug mode — set TOOLKIT_HOOK_DEBUG=true to enable verbose hook logging
TOOLKIT_HOOK_DEBUG="${TOOLKIT_HOOK_DEBUG:-false}"
export TOOLKIT_HOOK_DEBUG

# Gate bypass — set TOOLKIT_SKIP_GATES=lint,tests or TOOLKIT_SKIP_GATES=all
# to temporarily skip quality gates (useful for debugging false positives)
TOOLKIT_SKIP_GATES="${TOOLKIT_SKIP_GATES:-}"
export TOOLKIT_SKIP_GATES

# Custom hooks directory
export TOOLKIT_CUSTOM_HOOKS_DIR
TOOLKIT_CUSTOM_HOOKS_DIR="${CLAUDE_PROJECT_DIR:-.}/.claude/hooks-custom"

# ---------------------------------------------------------------------------
# Helper: iterate a JSON array stored in an env var
# Usage: toolkit_iterate_array "$TOOLKIT_HOOKS_SETUP_REQUIRED_TOOLS" | while read -r item; do ...
# ---------------------------------------------------------------------------
toolkit_iterate_array() {
  local json_array="${1:-[]}"
  if command -v jq >/dev/null 2>&1; then
    echo "$json_array" | jq -r '.[]' 2>/dev/null
  else
    # Fallback: strip brackets and quotes, split by comma
    echo "$json_array" | tr -d '[]"' | tr ',' '\n' | sed 's/^ *//'
  fi
}
